server:
  port: 8000

spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
      prod:
        - console-logging
        - file-logging

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/formdang-spring/**]':
            allow-credentials: true
            allowed-origins: "https://formdang.com/"
            allowed-headers: "*"
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS