server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: lawgg-web-spring
            uri: lb://LAWGG-WEB
            predicates:
              - Path=/lawgg/**
          - id: lawgg-admin-spring
            uri: lb://LAWGG-ADMIN
            predicates:
              - Path=/lawgg-ad-spring/**
          - id: formdang-api-spring
            uri: lb://FORMDANG-API
            predicates:
              - Path=/formdang-spring/**
          - id: formdang-auth-spring
            uri: lb://FORMDANG-AUTH
            predicates:
              - Path=/formdang-spring-auth/**

