eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

proxy:
  auth:
    url: http://localhost:22081/formdang-spring-auth/validate