server:
  port: 8000

spring:
  application:
    name: spring-cloud-gateway
  config:
    import: optional:configserver:http://spring-cloud-config:8888/ # spring cloud config 정보 조회 (서버 종료 option 처리)
#    import: optional:configserver:http://192.168.0.3:8888/ # spring cloud config 정보 조회 (서버 종료 option 처리)
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
      prod:
        - console-logging
        - file-logging